apiVersion: v1
kind: Service
metadata:
  name: apigee-lb
  namespace: apigee
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: apigee-ingressgateway #required
    ingress_name: apigee-ingress
    org: bnhp-apigeeh-poc
  type: LoadBalancer


---

apiVersion: v1
kind: Service
metadata:
  name: apigee-lb-dev
  namespace: apigee
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: apigee-ingressgateway #required
    ingress_name: dev-ingress
    org: bnhp-apigeeh-poc
  type: LoadBalancer


