kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: apigee-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

